### PR TITLE
Navigation menu changes to match the changes made in PolicyBrain PR #698

### PR DESCRIPTION
**Pull request by jessmc**
In this pull request:
- Navigation menu changes to match the changes made on PolicyBrain. 

Thanks!

### CODE REVIEW

**Comment by MattHJensen** [comment]
After doing some local testing, the top nav looks great,@jessmc, but the footer nav looks like it needs an update:

image

Could make sense to merge this and then do footer in a follow up PR. I'll leave that call to @hdoupe.

**Comment by hdoupe** [comment]
@MattHJensen What is your concern with the footer?

**Comment by MattHJensen** [comment]
> @MattHJensen What is your concern with the footer?

It uses different terms than the header. Notably "Apps" rather than "PolicyBrain."

Perhaps the right answer is to remove the footer entirely.

**Comment by hdoupe** [comment]
Ok, I see.  Well some sites have a footer and some don't.  It seems a little redundant to have both.  We could drop it for now and add it back in a subsequent PR if we want to.  How does that sound?

Another feature that we could add in a subsequent PR is highlighting the choices in the drop down menu as your mouse goes over them:
screen shot 2017-10-23 at 10 51 35 am

@MattHJensen @jessmc

**Comment by hdoupe** [comment]
Also, thanks @jessmc for the contribution.  This is a major improvement.

**Comment by MattHJensen** [comment]
@hdoupe said:

> It seems a little redundant to have both.  We could drop it for now and add it back in a subsequent PR if we want to.  How does that sound?

That sounds good. 

> Another feature that we could add in a subsequent PR is highlighting the choices in the drop down menu as your mouse goes over them:

That also sounds good.

**Comment by hdoupe** [comment]
@jessmc when do you think you'll have time to remove the footer?

**Comment by MattHJensen** [comment]
@hdoupe, what do you think about merging this and then opening an issue for sorting out the footer?

**Comment by hdoupe** [comment]
@MattHJensen Merging this makes sense.

**Pull request merged**
